#!/usr/bin/env python3
"""UCB1 matched-corpus, matched-donor pipeline and formula ablation.

Reuses frozen Serverledge code for reward prior, CRN and UCB1 traces.
Expects the LOFO file generated by compare_59_clustering_and_plots.py.
Only warm eligible invocation samples are used; target ARM never informs priors.
"""
from __future__ import annotations
import argparse
import hashlib
import json
from pathlib import Path

import numpy as np
import pandas as pd

from analysis.profiling.transfer_prior_formula_comparison import (
    load_eligible_durations, build_performance, make_crn_samples, build_prior,
)
from analysis.profiling.transfer_parameter_tuning_cv import (
    Config, simulate_baseline_trace, simulate_tl_trace,
    prefix_metrics_baseline, prefix_metrics_tl,
)

SCENARIOS = {
    'A_legacy_original': ('A_legacy_K5','difference',.25,1.,.8),
    'B_hybrid_original': ('B_hybrid_K6','difference',.25,1.,.8),
    'C_weighted_original': ('C_final_weighted','difference',.25,1.,.8),
    'C_lang025_original': ('C_lang025','difference',.25,1.,.8),
    'C_lang100_original': ('C_lang100','difference',.25,1.,.8),
    'D_weighted_difference_tuned': ('C_final_weighted','difference',.05,64.,.2),
    'E_weighted_ratio_tuned': ('C_final_weighted','ratio',.01,64.,.4),
    'C_lang025_difference_tuned': ('C_lang025','difference',.05,64.,.2),
    'C_lang100_difference_tuned': ('C_lang100','difference',.05,64.,.2),
}


def stable_seed(*parts):
    return int.from_bytes(hashlib.sha256('|'.join(map(str,parts)).encode()).digest()[:8], 'big') % 2**32


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def analyze(args):
    root=args.root.resolve(); out=args.output_dir.resolve()
    out.mkdir(parents=True,exist_ok=True)
    source=args.lofo_detail.resolve()
    if not source.is_file():raise SystemExit(f'Missing LOFO detail {source}')
    detail=pd.read_csv(source).fillna({'donor_function':''})
    required={'config','seed','target_function','status','donor_function'}
    if required-set(detail.columns):raise SystemExit(f'LOFO detail missing {sorted(required-set(detail.columns))}')
    if detail.duplicated(['config','seed','target_function']).any():raise SystemExit('Duplicate LOFO detail keys')
    seeds=sorted(detail.seed.unique().astype(int).tolist())
    raw_x=root/'raw/x86/all_samples.jsonl';raw_a=root/'raw/arm64/all_samples.jsonl'
    if not raw_x.is_file() or not raw_a.is_file():raise SystemExit('Missing raw JSONL in root/raw/{x86,arm64}')
    performance=build_performance(load_eligible_durations(raw_x), load_eligible_durations(raw_a))
    targets=sorted(set(detail.target_function))
    if len(targets)!=59:raise SystemExit(f'Expected 59 LOFO targets, got {len(targets)}')
    if not set(targets).issubset(performance):raise SystemExit('Missing performance data for target(s)')
    maps={}
    for cfg in sorted({v[0] for v in SCENARIOS.values()}):
        for seed in seeds:
            df=detail[(detail.config==cfg)&(detail.seed==seed)].set_index('target_function')
            if set(df.index)!=set(targets):raise SystemExit(f'Incomplete mapping {cfg}/{seed}')
            maps[(cfg,seed)]={t:(str(df.loc[t,'donor_function']) if df.loc[t,'status']=='selected' else None) for t in targets}
    for mapping in maps.values():
        for target,donor in mapping.items():
            if donor and (donor not in performance or donor==target):raise SystemExit(f'Invalid mapping {target}->{donor}')
    horizon=args.horizon; reps=args.replicates
    if horizon<1 or reps<1 or args.anchor_samples<1:raise SystemExit('Positive horizon, replicates and anchor needed')
    rows=[]
    for i,target in enumerate(targets,1):
        print(f'TL replay {i:02d}/59 {target}',flush=True)
        stats=performance[target]
        anchor,online=make_crn_samples(target=target,target_stats=stats,replicates=reps,max_horizon=horizon,
                                        anchor_n=args.anchor_samples,base_seed=args.mc_seed)
        # No transfer is identical across cluster seeds; compute once per target/repetition.
        baseline=[]
        for rep in range(reps):
            sequences={'x86':online['x86'][rep], 'arm64':online['arm64'][rep]}
            tr=simulate_baseline_trace(target_stats=stats,sequences=sequences,c=.8,convergence_run=5)
            baseline.append(prefix_metrics_baseline(tr,horizon))
        for seed in seeds:
            for strategy,(cfg,formula,wr,we,c) in SCENARIOS.items():
                donor=maps[(cfg,seed)][target]
                values=[]
                for rep in range(reps):
                    if not donor:
                        met=dict(baseline[rep]); met['gain_percent']=0.
                    else:
                        prior,_=build_prior(mode=formula,anchor_mean_reward_x86=float(anchor[rep]),
                                            donor_stats=performance[donor])
                        tr=simulate_tl_trace(target_stats=stats,
                              sequences={'x86':online['x86'][rep],'arm64':online['arm64'][rep]},
                              prior_mean_reward=prior,
                              config=Config(config_id=strategy,regime='frozen',w_r=wr,w_e=we,c=c),
                              convergence_run=5)
                        met=prefix_metrics_tl(tr,horizon)
                        met['gain_percent']=100*(baseline[rep]['cumulative_latency_ms']-met['cumulative_latency_ms'])/baseline[rep]['cumulative_latency_ms']
                    values.append(met)
                row=dict(target_function=target,seed=seed,strategy=strategy,donor_function=donor or '',
                         tl_applied=int(bool(donor)),horizon=horizon,replicates=reps,
                         formula=formula,w_r=wr,w_e=we,c=c)
                for metric in ['gain_percent','optimal_arm_rate','wrong_selections','cumulative_reward_pseudo_regret',
                               'cumulative_latency_ms','first_arm_optimal','convergence_probability','censored_convergence_request']:
                    row[metric]=float(np.mean([v[metric] for v in values]))
                rows.append(row)
    df=pd.DataFrame(rows)
    df.to_csv(out/'ucb1_59_per_target_seed.csv',index=False)
    # Average seed over each target BEFORE taking macro means and CIs.
    numeric=['gain_percent','optimal_arm_rate','wrong_selections','cumulative_reward_pseudo_regret',
             'cumulative_latency_ms','first_arm_optimal','convergence_probability','censored_convergence_request','tl_applied']
    per_target=df.groupby(['target_function','strategy'],as_index=False)[numeric].mean()
    per_target.to_csv(out/'ucb1_59_per_target.csv',index=False)
    summary=per_target.groupby('strategy',as_index=False)[numeric].mean()
    summary.to_csv(out/'ucb1_59_summary.csv',index=False)
    comparisons=[]
    pairs=[('A_legacy_original','B_hybrid_original'),('B_hybrid_original','C_weighted_original'),
           ('A_legacy_original','C_weighted_original'),
           ('C_weighted_original','D_weighted_difference_tuned'),
           ('D_weighted_difference_tuned','E_weighted_ratio_tuned'),
           ('C_weighted_original','C_lang025_original'),('C_weighted_original','C_lang100_original'),
           ('D_weighted_difference_tuned','C_lang025_difference_tuned'),
           ('D_weighted_difference_tuned','C_lang100_difference_tuned')]
    for a,b in pairs:
        aa=per_target[per_target.strategy==a].set_index('target_function')
        bb=per_target[per_target.strategy==b].set_index('target_function')
        if set(aa.index)!=set(bb.index):raise AssertionError('Unpaired targets')
        rng=np.random.default_rng(stable_seed(args.bootstrap_seed,a,b))
        for metric in ['gain_percent','optimal_arm_rate','wrong_selections','cumulative_reward_pseudo_regret']:
            diff=(bb.loc[targets,metric]-aa.loc[targets,metric]).to_numpy(float)
            inds=rng.integers(0,len(targets),size=(args.bootstrap_replicates,len(targets)))
            means=diff[inds].mean(axis=1)
            comparisons.append(dict(comparison=f'{b}_minus_{a}',metric=metric,
                         point_delta=float(diff.mean()),ci95_low=float(np.quantile(means,.025)),
                         ci95_high=float(np.quantile(means,.975)),paired_targets=59))
    ci=pd.DataFrame(comparisons)
    ci.to_csv(out/'ucb1_59_paired_ci.csv',index=False)
    text=['# UCB1: confronto controllato delle vecchie e nuove pipeline (59 target)','',
          'Esperimento **nuovo**: non riutilizzare le percentuali della vecchia presentazione come controllo.',
          '','## Matrice delle variazioni',
          '- A: vecchio PAPER5/K5, nearest Manhattan, Difference originale',
          '- B: ibrido/K6, stesso nearest Manhattan e Difference originale',
          '- C: ibrido/K6, weighted vote 1/d² e Difference originale',
          '- D: C + Difference tuned (w_R=.05, w_E=64, c=.2)',
          '- E: C + Ratio tuned (w_R=.01, w_E=64, c=.4)',
          '- Lingua: C con one-hot 0.25 / 1 a configurazione TL originale e tuned fissata',
          '','## Controlli',
          f'- Stessi 59 target, seed clustering {seeds}, replicates {reps}, H={horizon}',
          f'- Target x86 anchor da {args.anchor_samples} campioni warm bootstrap, stream separato dall’online.',
          '- Common random numbers (CRN) identici per tutte le strategie; no-transfer UCB1 c=.8.',
          '- Le informazioni ARM del **target** non entrano in donor search né prior; solo replay/posthoc.',
          '- Astensione donor: replay identico a no-transfer (non si eliminano target).',
          '- Prima si aggrega sul seed per target, poi si fa macro media sui 59 target.',
          '- CI95% paired bootstrap percentile sui 59 target: valori non significativi se intervallo del delta include 0.',
          '', '## Risultati',
          '| Strategia | Gain latenza vs noTL | Optimal arm | Wrong H | Pseudo-regret | TL coverage |',
          '|---|---:|---:|---:|---:|---:|']
    for _,r in summary.iterrows():
        text.append(f"| {r.strategy} | {r.gain_percent:+.4f}% | {r.optimal_arm_rate:.4f} | {r.wrong_selections:.3f} | {r.cumulative_reward_pseudo_regret:.4f} | {r.tl_applied:.2%} |")
    text+=['','## Paired differences',
           '| Confronto | Delta gain (pp) | CI95% low | CI95% high |','|---|---:|---:|---:|']
    for _,r in ci[ci.metric=='gain_percent'].iterrows():
        text.append(f'| {r.comparison} | {r.point_delta:+.4f} | {r.ci95_low:+.4f} | {r.ci95_high:+.4f} |')
    text+=['','Questi risultati sono **offline**. Le differenze tra donor rules non vanno confuse con l’effetto del tuning del bandit.',
           '', '## Provenienza',f'- LOFO donor mappings `{source}` SHA256 `{sha(source)}`',
           f'- Raw x86 `{raw_x}` SHA256 `{sha(raw_x)}`',f'- Raw arm64 `{raw_a}` SHA256 `{sha(raw_a)}`']
    (out/'UCB1_59_REPORT.md').write_text('\n'.join(text)+'\n',encoding='utf-8')
    (out/'ucb1_59_manifest.json').write_text(json.dumps({'seed':args.mc_seed,'bootstrap_seed':args.bootstrap_seed,
                   'anchor_samples':args.anchor_samples,'replicates':reps,'horizon':horizon,
                   'cluster_seeds':seeds,'inputs':{'lofo':sha(source),'raw_x86':sha(raw_x),'raw_arm':sha(raw_a)},
                   'scenarios':SCENARIOS},indent=2)+'\n')
    print('PASS: finished paired UCB1 replay on 59 functions; summary:')
    print(summary.to_string(index=False,float_format=lambda x:f'{x:.4f}'))
    print('REPORT:',out/'UCB1_59_REPORT.md')


def main():
    p=argparse.ArgumentParser()
    p.add_argument('--root',type=Path,required=True)
    p.add_argument('--lofo-detail',type=Path,required=True)
    p.add_argument('--output-dir',type=Path,required=True)
    p.add_argument('--replicates',type=int,default=200)
    p.add_argument('--horizon',type=int,default=10)
    p.add_argument('--anchor-samples',type=int,default=10)
    p.add_argument('--mc-seed',type=int,default=2026100816)
    p.add_argument('--bootstrap-replicates',type=int,default=5000)
    p.add_argument('--bootstrap-seed',type=int,default=2026100817)
    analyze(p.parse_args())

if __name__=='__main__':main()
